### No Need To Run This Notebook!
This notebook is only here to show how the country recommender was made.

In [ ]:
import pandas as pd

In [ ]:
%run import_data_.py

Continuing with existing version of data folder
Goodreads dataset loaded successfully as books_goodreads
Pandas dataframes (books_goodreads, books_big, book, users, ratings) loaded successfully
Columns in DataFrames 'users' and 'ratings' renamed
You can use the DataFrames 'books' or 'books_big' - they are exactly the same (big) dataset
loading books_ratings and books_users_ratings
Ready to go!

In [ ]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   user_id   278858 non-null  int64
 1   location  278858 non-null  object
 2   age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

In [ ]:
users.head()

   user_id                            location   age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [ ]:
%pip install pycountry

Collecting pycountry
  Downloading pycountry-24.6.1-py3-none-any.whl.metadata (12 kB)
Downloading pycountry-24.6.1-py3-none-any.whl (6.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.3/6.3 MB 7.0 MB/s eta 0:00:00[31m7.1 MB/s eta 0:00:01
Installing collected packages: pycountry
Successfully installed pycountry-24.6.1
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pycountry

# Function to extract country using pycountry
def get_country_from_location(location):
    for country in pycountry.countries:
        if country.name.lower() in location.lower():
            return country.name
        elif ", usa" in location.lower():
            return "United States"
        elif ", russia" in location.lower():
            return "Russian Federation"
    return None

# Apply function
users['country'] = users['location'].apply(get_country_from_location)
users.head()

   user_id                            location   age             country
0        1                  nyc, new york, usa   NaN       United States
1        2           stockton, california, usa  18.0       United States
2        3     moscow, yukon territory, russia   NaN  Russian Federation
3        4           porto, v.n.gaia, portugal  17.0            Portugal
4        5  farnborough, hants, united kingdom   NaN      United Kingdom

In [ ]:
users.country.describe()

count            271664
unique              181
top       United States
freq             139731
Name: country, dtype: object

In [ ]:
users.isna().sum()

user_id          0
location         0
age         110762
country       7194
dtype: int64

In [ ]:
countries = [country.name for country in pycountry.countries]
print(countries)

['Aruba', 'Afghanistan', 'Angola', 'Anguilla', 'Åland Islands', 'Albania', 'Andorra', 'United Arab Emirates', 'Argentina', 'Armenia', 'American Samoa', 'Antarctica', 'French Southern Territories', 'Antigua and Barbuda', 'Australia', 'Austria', 'Azerbaijan', 'Burundi', 'Belgium', 'Benin', 'Bonaire, Sint Eustatius and Saba', 'Burkina Faso', 'Bangladesh', 'Bulgaria', 'Bahrain', 'Bahamas', 'Bosnia and Herzegovina', 'Saint Barthélemy', 'Belarus', 'Belize', 'Bermuda', 'Bolivia, Plurinational State of', 'Brazil', 'Barbados', 'Brunei Darussalam', 'Bhutan', 'Bouvet Island', 'Botswana', 'Central African Republic', 'Canada', 'Cocos (Keeling) Islands', 'Switzerland', 'Chile', 'China', "Côte d'Ivoire", 'Cameroon', 'Congo, The Democratic Republic of the', 'Congo', 'Cook Islands', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica', 'Cuba', 'Curaçao', 'Christmas Island', 'Cayman Islands', 'Cyprus', 'Czechia', 'Germany', 'Djibouti', 'Dominica', 'Denmark', 'Dominican Republic', 'Algeria', 'Ecuador', 'Egypt', 'Eritrea', 'Western Sahara', 'Spain', 'Estonia', 'Ethiopia', 'Finland', 'Fiji', 'Falkland Islands (Malvinas)', 'France', 'Faroe Islands', 'Micronesia, Federated States of', 'Gabon', 'United Kingdom', 'Georgia', 'Guernsey', 'Ghana', 'Gibraltar', 'Guinea', 'Guadeloupe', 'Gambia', 'Guinea-Bissau', 'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala', 'French Guiana', 'Guam', 'Guyana', 'Hong Kong', 'Heard Island and McDonald Islands', 'Honduras', 'Croatia', 'Haiti', 'Hungary', 'Indonesia', 'Isle of Man', 'India', 'British Indian Ocean Territory', 'Ireland', 'Iran, Islamic Republic of', 'Iraq', 'Iceland', 'Israel', 'Italy', 'Jamaica', 'Jersey', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya', 'Kyrgyzstan', 'Cambodia', 'Kiribati', 'Saint Kitts and Nevis', 'Korea, Republic of', 'Kuwait', "Lao People's Democratic Republic", 'Lebanon', 'Liberia', 'Libya', 'Saint Lucia', 'Liechtenstein', 'Sri Lanka', 'Lesotho', 'Lithuania', 'Luxembourg', 'Latvia', 'Macao', 'Saint Martin (French part)', 'Morocco', 'Monaco', 'Moldova, Republic of', 'Madagascar', 'Maldives', 'Mexico', 'Marshall Islands', 'North Macedonia', 'Mali', 'Malta', 'Myanmar', 'Montenegro', 'Mongolia', 'Northern Mariana Islands', 'Mozambique', 'Mauritania', 'Montserrat', 'Martinique', 'Mauritius', 'Malawi', 'Malaysia', 'Mayotte', 'Namibia', 'New Caledonia', 'Niger', 'Norfolk Island', 'Nigeria', 'Nicaragua', 'Niue', 'Netherlands', 'Norway', 'Nepal', 'Nauru', 'New Zealand', 'Oman', 'Pakistan', 'Panama', 'Pitcairn', 'Peru', 'Philippines', 'Palau', 'Papua New Guinea', 'Poland', 'Puerto Rico', "Korea, Democratic People's Republic of", 'Portugal', 'Paraguay', 'Palestine, State of', 'French Polynesia', 'Qatar', 'Réunion', 'Romania', 'Russian Federation', 'Rwanda', 'Saudi Arabia', 'Sudan', 'Senegal', 'Singapore', 'South Georgia and the South Sandwich Islands', 'Saint Helena, Ascension and Tristan da Cunha', 'Svalbard and Jan Mayen', 'Solomon Islands', 'Sierra Leone', 'El Salvador', 'San Marino', 'Somalia', 'Saint Pierre and Miquelon', 'Serbia', 'South Sudan', 'Sao Tome and Principe', 'Suriname', 'Slovakia', 'Slovenia', 'Sweden', 'Eswatini', 'Sint Maarten (Dutch part)', 'Seychelles', 'Syrian Arab Republic', 'Turks and Caicos Islands', 'Chad', 'Togo', 'Thailand', 'Tajikistan', 'Tokelau', 'Turkmenistan', 'Timor-Leste', 'Tonga', 'Trinidad and Tobago', 'Tunisia', 'Türkiye', 'Tuvalu', 'Taiwan, Province of China', 'Tanzania, United Republic of', 'Uganda', 'Ukraine', 'United States Minor Outlying Islands', 'Uruguay', 'United States', 'Uzbekistan', 'Holy See (Vatican City State)', 'Saint Vincent and the Grenadines', 'Venezuela, Bolivarian Republic of', 'Virgin Islands, British', 'Virgin Islands, U.S.', 'Viet Nam', 'Vanuatu', 'Wallis and Futuna', 'Samoa', 'Yemen', 'South Africa', 'Zambia', 'Zimbabwe']

In [ ]:
# Merge df1 with df2 to add 'country' to df1
books_users_ratings = pd.merge(books_users_ratings, users[['user_id', 'country']], on='user_id', how='left')

In [ ]:
books_users_ratings.head()

,isbn,book_title,book_author,user_id,individual_rating,avg_rating,nr_ratings,nr_readers,genre,year_of_publication,publisher,annotations,mod_title,mod_author,mod_publisher,image_url_s,image_url_m,image_url_l,country
0,590085417,Heidi,Johanna Spyri,102967.0,8.0,8.0,2,3,"['Juvenile Fiction', 'Fiction', ""Children's Li...",2021,Scholastic,Heidi (Fictitious character : Spyri),heidi,johanna spyri,scholastic,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,United States
1,590085417,Heidi,Johanna Spyri,111702.0,8.0,8.0,2,3,"['Juvenile Fiction', 'Fiction', ""Children's Li...",2021,Scholastic,Heidi (Fictitious character : Spyri),heidi,johanna spyri,scholastic,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,United States
2,590085417,Heidi,Johanna Spyri,135473.0,0.0,8.0,2,3,"['Juvenile Fiction', 'Fiction', ""Children's Li...",2021,Scholastic,Heidi (Fictitious character : Spyri),heidi,johanna spyri,scholastic,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,None
3,68107468X,Edgar Allen Poe Collected Poems,Edgar Allan Poe,204964.0,8.0,8.0,2,2,['Poetry'],2020,Bausch & Lombard,NaN,edgar allen poe collected poems,edgar allan poe,bausch lombard,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,United States
4,68107468X,Edgar Allen Poe Collected Poems,Edgar Allan Poe,267830.0,8.0,8.0,2,2,['Poetry'],2020,Bausch & Lombard,NaN,edgar allen poe collected poems,edgar allan poe,bausch lombard,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,United States

In [ ]:
books_users_ratings.country.value_counts()

country
United States       682844
Canada               83373
United Kingdom       29052
Germany              16648
Australia            15809
                     ...
Algeria                  1
Zambia                   1
Palau                    1
Marshall Islands         1
Lebanon                  1
Name: count, Length: 132, dtype: int64

In [ ]:
books_users_ratings.country.info()

<class 'pandas.core.series.Series'>
RangeIndex: 917916 entries, 0 to 917915
Series name: country
Non-Null Count   Dtype
--------------   -----
883089 non-null  object
dtypes: object(1)
memory usage: 7.0+ MB

In [ ]:
# Recommendation function based on top rated books in a specific country:
def recommender_country(books_users_ratings, country="United States"):
    recommendations = books_users_ratings[books_users_ratings['country' == country]]
    recommendations = recommendations.sort_values(by=['avg_rating', 'nr_ratings'], ascending=[False, False])
    recommendations = recommendations.drop_duplicates(subset='isbn')
    recommendations = recommendations.head(10)
    return recommendations[['isbn', 'book_title', 'image_url_m']]

In [ ]:
books_users_ratings.head()

,isbn,book_title,book_author,user_id,individual_rating,avg_rating,nr_ratings,nr_readers,genre,year_of_publication,publisher,annotations,mod_title,mod_author,mod_publisher,image_url_s,image_url_m,image_url_l,country
0,590085417,Heidi,Johanna Spyri,102967.0,8.0,8.0,2,3,"['Juvenile Fiction', 'Fiction', ""Children's Li...",2021,Scholastic,Heidi (Fictitious character : Spyri),heidi,johanna spyri,scholastic,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,United States
1,590085417,Heidi,Johanna Spyri,111702.0,8.0,8.0,2,3,"['Juvenile Fiction', 'Fiction', ""Children's Li...",2021,Scholastic,Heidi (Fictitious character : Spyri),heidi,johanna spyri,scholastic,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,United States
2,590085417,Heidi,Johanna Spyri,135473.0,0.0,8.0,2,3,"['Juvenile Fiction', 'Fiction', ""Children's Li...",2021,Scholastic,Heidi (Fictitious character : Spyri),heidi,johanna spyri,scholastic,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,http://images.amazon.com/images/P/0590085417.0...,None
3,68107468X,Edgar Allen Poe Collected Poems,Edgar Allan Poe,204964.0,8.0,8.0,2,2,['Poetry'],2020,Bausch & Lombard,NaN,edgar allen poe collected poems,edgar allan poe,bausch lombard,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,United States
4,68107468X,Edgar Allen Poe Collected Poems,Edgar Allan Poe,267830.0,8.0,8.0,2,2,['Poetry'],2020,Bausch & Lombard,NaN,edgar allen poe collected poems,edgar allan poe,bausch lombard,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,http://images.amazon.com/images/P/068107468X.0...,United States

In [ ]:
# books_users_ratings.to_csv("../data/books_users_ratings.csv", sep=";", encoding="utf-8-sig", index=False)